language: python

sudo: false

python:
  - "3.5"
  - "3.6"

  # PyPy versions
  - "pypy3.5-5.10"

install:
  - pip install pipenv
  - pipenv install --dev --deploy

script:
  - pipenv run py.test --maxfail=2 --durations=3 --cov=mimesis --benchmark-skip
  - pipenv run mypy mimesis

after_success:
  codecov

before_deploy:
  - python setup.py minify

deploy:
  provider: pypi
  user: lk-geimfari
  password: $SECURE_PASS
  distributions: sdist bdist_wheel
  on:
    branch: master
    tags: true

notifications:
  email:
    on_success: never
    on_failure: change
