language: python

sudo: false

python:
  - "3.5"
  - "3.6"

install: pip install -r dev_requirements.txt

script:
  - py.test --cov=mimesis/
  - mypy mimesis/

after_success:
  codecov

before_deploy:
  - python setup.py minify

deploy:
  provider: pypi
  user: lk-geimfari
  password: $SECURE_PASS
  on:
    branch: master
    tags: true
