language: python

sudo: false

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

install:
  - pip install codecov
  - pip install pytest-cov
  - pip install flake8-builtins
  - pip install flake8-commas
  - pip install flake8-quotes
  - pip install pytest-flake8
  - pip install pytest-isort

script: py.test --cov=mimesis/

after_success:
  codecov
