language: python

sudo: false

python:
  - "3.5"
  - "3.6"

install: pip install -r dev_requirements.txt

script:
  - py.test --maxfail=2 --durations=3 --cov=mimesis --benchmark-skip
  - mypy mimesis

after_success:
  codecov

before_deploy:
  - python setup.py minify

deploy:
  provider: pypi
  user: lk-geimfari
  password: $SECURE_PASS
  distributions: sdist bdist_wheel
  on:
    branch: master
    tags: true

notifications:
  email:
    on_success: never
    on_failure: change
