environment:
  matrix:

    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"

    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"

install:
  - "%PYTHON%\\python.exe -m pip install pipenv"
  - "%PYTHON%\\python.exe -m pipenv install --dev --deploy"

build: off

test_script:
  - "%PYTHON%\\python.exe -m pipenv run py.test --maxfail=2 --durations=3 --cov=mimesis --benchmark-skip"
