[pytest]
flake8-statistics = true
flake8-max-line-length = 80

flake8-inline-quotes = '
flake8-ignore =
  docs/conf.py ALL
  mimesis/data/__init__.py ALL
  mimesis/data/int/*.py ALL
  mimesis/__init__.py F403
  tests/*.py F841
  setup.py ALL

addopts =
    --cache-clear
    --flake8
    --isort
